openapi: 3.0.3
info:
  version: 0.3.0
  title: Supaglue API
  contact:
    name: Supaglue
    email: docs@supaglue.com
    url: 'https://supaglue.com'
  description: |
    # Introduction

    Welcome to the Supaglue unified CRM API documentation. You can use this API to read data that has been synced into Supaglue from third-party providers.

    ### Base API URL

    ```
    http://localhost:8080/api/crm/v1
    ```
externalDocs:
  description: Try out our API in Postman!
  url: 'https://www.postman.com/supaglue/workspace/supaglue-public/overview'
servers:
  - url: 'https://localhost:8080/crm/v1'
    description: Local Supaglue API
paths:
  '/accounts':
    $ref: paths/accounts.yaml
  '/accounts/{account_id}':
    $ref: paths/accounts@{account_id}.yaml
  '/contacts':
    $ref: paths/contacts.yaml
  '/contacts/{contact_id}':
    $ref: paths/contacts@{contact_id}.yaml
  '/leads':
    $ref: paths/leads.yaml
  '/leads/{lead_id}':
    $ref: paths/leads@{lead_id}.yaml
  '/opportunities':
    $ref: paths/opportunities.yaml
  '/opportunities/{opportunity_id}':
    $ref: paths/opportunities@{opportunity_id}.yaml
  '/sync-info':
    $ref: paths/sync-info.yaml
tags:
  - name: Accounts
    description: The `Account` Common Model is used to represent a "company" in CRMs.
  - name: Contacts
    description: The `Contact` Common Model is used to represent a "contact" in CRMs.
  - name: Leads
    description: The `Lead` Common Model is used to represent a "potential customer" in CRMs.
  - name: Opportunities
    description: The `Opportunity` Common Model is used to represent a "deal opportunity" in CRMs.
  - name: SyncInfo
    description: (Non-CRM) `SyncInfo` provides metadata about a `Sync`.
components:
  schemas:
    account:
      $ref: ./components/schemas/objects/account.yaml
    create_update_account:
      $ref: ./components/schemas/create_update_account.yaml
    contact:
      $ref: ./components/schemas/objects/contact.yaml
    create_update_contact:
      $ref: ./components/schemas/create_update_contact.yaml
    lead:
      $ref: ./components/schemas/objects/lead.yaml
    create_update_lead:
      $ref: ./components/schemas/create_update_lead.yaml
    opportunity:
      $ref: ./components/schemas/objects/opportunity.yaml
    create_update_opportunity:
      $ref: ./components/schemas/create_update_opportunity.yaml
    logs:
      $ref: ./components/schemas/logs.yaml
    errors:
      $ref: ./components/schemas/errors.yaml
    warnings:
      $ref: ./components/schemas/warnings.yaml
    addresses:
      $ref: ./components/schemas/objects/addresses.yaml
    email_addresses:
      $ref: ./components/schemas/objects/email_addresses.yaml
    phone_numbers:
      $ref: ./components/schemas/objects/phone_numbers.yaml
    pagination:
      $ref: ./components/schemas/pagination.yaml
  # TODO: uncomment when we implement API authentication
  # securitySchemes:
  #   api_key:
  #     type: apiKey
  #     name: X-Account-Token
  #     in: header
  #     description: Token identifying the end user
  parameters:
    created_after:
      $ref: ./components/parameters/created_after.yaml
    created_before:
      $ref: ./components/parameters/created_before.yaml
    updated_after:
      $ref: ./components/parameters/updated_after.yaml
    updated_before:
      $ref: ./components/parameters/updated_before.yaml
    cursor:
      $ref: ./components/parameters/cursor.yaml
    expand:
      $ref: ./components/parameters/expand.yaml
    page_size:
      $ref: ./components/parameters/page_size.yaml
